// female page data 
let shopItemsData2 = [
  {
    id: "1.1",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/saree 1.jpg",
  },
  {
    id: "1.2",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/saree 2.jpg",
  },
  {
    id: "1.3",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/saree 3.jpg",
  },
  {
    id: "1.4",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/saree 4.jpg",
  },
  {
    id: "1.5",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/suit 1.jpg",
  },
  {
    id: "1.6",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/suit 2.jpg",
  },
  
  {
    id: "1.7",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/suit 3.jpg",
  },
  {
    id: "1.8",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/suit 4.jpg",
  },
  {
    id: "1.9",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/jeans 1.jpg",
  },
  {
    id: "1.10",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/jeans 2.jpg",
  },
  {
    id: "1.11",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/jeans 3.jpg",
  },
  {
    id: "1.12",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/jeans 4.jpg",
  },
  {
    id: "1.13",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/top1.jpg",
  },
  {
    id: "1.14",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/top2.jpg",
  },
  {
    id: "1.15",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/top 3.jpg",
  },
  {
    id: "1.16",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/top 4.jpg",
  },
  
];
// kid pagee data 
let shopItemsData = [
  {
    id: "1",
    name: "Shirt Pant",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k1.jpg",
  },
  {
    id: "2",
    name: "Long Frock",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k2.jpg",
  },
  {
    id: "3",
    name: "Gown",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k3.jpg",
  },
  {
    id: "4",
    name: "Wedding Dress",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k4.jpg",
  },
  {
    id: "5",
    name: "Shirt pant",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k5.jpg",
  },
  {
    id: "6",
    name: "Frock",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k6.jpg",
  },
  {
    id: "7",
    name: "Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k7.jpg",
  },
  {
    id: "8",
    name: "Shervani",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k8.jpg",
  },
  {
    id: "9",
    name: "Dangri",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k9.jpg",
  },
  {
    id: "10",
    name: "Shirt Pant",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k10.jpg",
  },
  {
    id: "11",
    name: "Lehnga",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k11.jpg",
  },
  {
    id: "12",
    name: "Winter wear",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k12.jpg",
  },
  {
    id: "13",
    name: "Dress",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k13.jpg",
  },
  {
    id: "14",
    name: "Frock",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k14.jpg",
  },
  {
    id: "15",
    name: "Kurta pant",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k15.jpg",
  },
  {
    id: "16",
    name: "Saree",
    price: 500,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "img/k16.jpg",
  },
  
];
// to get the dommy paragraph (word in paragraph).... supopose i need only 8 words so i will write lorem8 and enter, same if i need 100 words ill write lorem100 and enter 
